config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :topics, only: [:index, :show]
  
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me',      to: 'pages#about'
  get 'contact',       to: 'pages#contact'
  get 'tech-news',     to: 'pages#tech_news'

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Edward Kruljac</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header> 

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>&copy; <%= "#{Time.now.year}" %> | <b>Edward Kruljac</b> All rights reserved</p>
  <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
          <div class="bg-light p-4">
            <ul class="list-unstyled">
              <%= nav_helper 'p-2 text-blue', 'li' %>
            </ul>
          </div>
        </div>
        <nav class="navbar navbar-dark bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </nav>
      </div>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Edward's Blog</a>
      <p><%= link_to 'Write A New Blog', new_blog_path if logged_in?(:site_admin) %></p>
      <%= link_to "Browse By Topic", topics_path, class: 'btn btn-primary' %>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= login_helper "btn btn-sm btn-outline-primary" %>
    </div>
  </div>
</header> 

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">This is my blog.  There are many like it but this one is mine.
    My blog is my best friend.  It is my life.  I must master it as I must master
    my life.  Without me, my blog is useless. Without my blog, <em>I</em> am useless.</p>
  </div>

  <div class="sidebar-module">
    <%= source_helper('alert alert-info') %>
  </div>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Find Me Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_footer.html.erb
<footer class="app-footer">
  <p>&copy; <%= "#{Time.now.year}" %> | <b>Edward Kruljac</b> All rights reserved</p>
  <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= nav_helper 'nav-link', 'span' %>
</div> 

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">In this portfolio I've listed my favorite projects I've built. These applications capture a wide range of the projects that I am especially proud of.</p>
    <p>
      <%= link_to "About Me", about_me_path, class: 'btn btn-primary' %>
      <%= link_to "My Blog", blogs_path, class: 'btn btn-secondary' %>
      <%= link_to "Contact Me", contact_path, class: 'btn btn-info' %>
      <%= link_to "All Portfolio Items", portfolios_path, class: 'btn btn-info' unless current_page? portfolios_path %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-sm-4 pt-1">
      <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
          <div class="bg-light p-4">
            <ul class="list-unstyled">
              <%= nav_helper 'p-2 text-blue', 'li' %>
            </ul>
          </div>
        </div>
        <nav class="navbar navbar-dark bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </nav>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <a class="blog-header-logo text-dark" href="#">My Portfolio</a>
    </div>
    <div class="col-sm-4 d-flex justify-content-end align-items-center">
      <%= login_helper "btn btn-sm btn-outline-primary" %>
    </div>
  </div>
</header>
  